# Generated by Django 5.0.2 on 2024-02-14 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_out', models.TimeField(blank=True, null=True)),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
