# Generated by Django 5.0.2 on 2024-02-14 10:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='check_in',
            field=models.TimeField(default=datetime.datetime(2024, 2, 14, 10, 43, 24, 229407)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendance',
            name='checkin_date',
            field=models.DateField(default=datetime.datetime(2024, 2, 14, 10, 43, 33, 640470)),
            preserve_default=False,
        ),
    ]
